version: '3.7'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - TZ=America/Sao_Paulo
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    environment:
      - TZ=America/Sao_Paulo

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    volumes:
      - bundle_cache:/bundle
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
      - TZ=America/Sao_Paulo
      - DATABASE_URL=postgresql://postgres:password@db:5432/code-challenge?encoding=utf8&pool=5&timeout=5000
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

volumes:
  bundle_cache:
